### PR TITLE
Fix address usage, export message id in MessageWrapper and update tests

### LINKED ISSUE #286: fix nodejs tests

### PR DESCRIPTION
**Pull request by Thoralf-M**
milestone metadata still needs to be fixed and we need an option to get the message id from a message (wrapper around the message object, function to calculate it or both)

### CODE REVIEW

**Comment by Thoralf-M** [comment]
Fixes #286

File: bindings/nodejs/tests/client.js [hunk 1]
```diff
@@ -2,12 +2,11 @@ const { ClientBuilder } = require('../lib')
 const { assertAddress, assertMessageId, assertMessage } = require('./assertions')
 const assert = require('assert')
 
-const seed = 'b3a9bf35521157aa9c4508ab3a9266e210ae297ff5a4584234c4d9e7d01712e3'
```
Comment (lucasfernog) [inline bindings/nodejs/tests/client.js:5]: we should probably use a env here in the future

**Review by lucasfernog — APPROVED** [review]
