### PR TITLE
Use OutputMetadataDto instead of OutputMetadata

### LINKED ISSUE #1547: [Bug]: `InputSigningDataDto` incompatible with NodeJS binding
### Issue description

I'm exposing an API (`SecretManager::signature_unlock`) in the nodejs bindings and when testing that I ran into some issues. I wanted to validate that the behavior on the nodejs API is the same as in Rust. In Rust I create a `PreparedTransactionDataDto` and serialize that. The result is used in a nodejs test as the input for the above API to then assert that, given the same secret managers with the same mnemonic, they produce the same `Unlock` for a certain input of the transaction.

### Version

`a2d98bc0` (`develop` branch from yesterday).

### Expected behaviour

I expect to be able to serialize `PreparedTransactionDataDto` as JSON and use the result as an object in TS of type `IPreparedTransactionData`.

### Actual behaviour

Three errors/problems occur when doing that.

1. `PreparedTransactionDataDto` contains an `InputSigningDataDto` which [contains `OutputMetadata`](https://github.com/iotaledger/iota.rs/blob/595da10d75f3d746a45c8dfda6561399ab71a435/client/src/secret/types.rs#L159). Note that the latter is not the `Dto` type. That results in additional fields being present in the resulting JSON and some required ones missing. I assume this should be changed to `OutputMetadataDto`?
2. `InputSigningDataDto` serializes its [`output_metadata` field as `outputMetadata`](https://github.com/iotaledger/iota.rs/blob/595da10d75f3d746a45c8dfda6561399ab71a435/client/src/secret/types.rs#L158) but in NodeJS this is defined as [`outputMetaData`](https://github.com/iotaledger/iota.rs/blob/595da10d75f3d746a45c8dfda6561399ab71a435/client/bindings/nodejs/types/preparedTransactionData.ts#L40) (note the different capitalization).
3. `InputSigningDataDto` contains an [`Option<Chain>` field](https://github.com/iotaledger/iota.rs/blob/595da10d75f3d746a45c8dfda6561399ab71a435/client/src/secret/types.rs#L159) which is a newtype wrapper around `Vec<Segment>`. That serialization is not entirely compatible with the corresponding [TS definition](https://github.com/iotaledger/iota.rs/blob/595da10d75f3d746a45c8dfda6561399ab71a435/client/bindings/nodejs/types/preparedTransactionData.ts). Note `ISegment`'s `bs` field which is a `Uint8Array`. The issue is that `Uint8Array`'s serialization is different from Rust arrays. The latter expects JSON like `[1,2,3,4]` while `Uint8Array` produces `{"0":1,"1":2,"2":3,"3":4}`. This leads to deserialization problems when sending JSON over the message interface and attempting to deserialize it into a `Message`. A potential fix might be to use `number[]`. Trying to deserialize anything outside the byte range into `[u8; 4]` would be caught by serde, but double checking that would be good.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Run steps 1 and 2 of the offline signing example.
2. Copy the contents of `prepared_transaction.json` into an example file in the NodeJS bindings and try assigning it to some constant of type `IPreparedTransactionData`.
3. Notice the errors. To see the above-mentioned errors, one has to deal with the `bs` fields not being of type `Uint8Array` first. That can be temporarily fixed by wrapping these in `Uint8Array.from` (or deleting them).

### Errors

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Use OutputMetadataDto instead of OutputMetadata

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota.rs/issues/1547

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Running offline signing examples

Philipp wrote `Trying to deserialize anything outside the byte range into [u8; 4] would be caught by serde, but double checking that would be good.` in the issue, so I tried to run it with `"bs": [128, 0, 0, 44, 1]` instead of `"bs": [128, 0, 0, 44]` and it returned `Error("trailing characters", line: 1, column: 1644)`, so should be good

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: client/bindings/nodejs/examples/offline_signing/1_transaction_preparation.ts [hunk 1]
```diff
@@ -1,10 +1,10 @@
 // Copyright 2021-2022 IOTA Stiftung
 // SPDX-License-Identifier: Apache-2.0
 
-import { Client, initLogger } from '@iota/client';
+import { Client, initLogger, IPreparedTransactionData } from '@iota/client';
```
Comment (thibault-martinez) [inline client/bindings/nodejs/examples/offline_signing/1_transaction_preparation.ts]: Warning

File: client/src/secret/types.rs [hunk 2]
```diff
@@ -156,7 +159,7 @@ pub struct InputSigningDataDto {
     pub output: OutputDto,
     /// The output metadata
     #[serde(rename = "outputMetadata")]
-    pub output_metadata: OutputMetadata,
+    pub output_metadata: OutputMetadataDto,
```
Comment (thibault-martinez) [inline client/src/secret/types.rs:162]: Are we 100% sure this doesn't cause any issue with stored data ?

File: client/bindings/nodejs/types/preparedTransactionData.ts [hunk 3]
```diff
@@ -65,5 +65,5 @@ export interface IRemainder {
 }
 export interface ISegment {
     hardened: boolean;
-    bs: Uint8Array;
+    bs: number[];
```
Comment (thibault-martinez) [inline client/bindings/nodejs/types/preparedTransactionData.ts:68]: Maybe elaborate the changelog a tiny bit more

File: client/src/secret/types.rs (hunk 2 above)
Comment (Thoralf-M) [reply client/src/secret/types.rs:162]: Checked in the wallet, there we only use `InputSigningData` and not the DTO and also that we only create during the input selection, but don't store it

File: client/bindings/nodejs/types/preparedTransactionData.ts (hunk 3 above)
Comment (Thoralf-M) [reply client/bindings/nodejs/types/preparedTransactionData.ts:68]: Please check now

**Review by thibault-martinez — APPROVED** [review]

**Review by kwek20 — APPROVED** [review]
