### PR TITLE
Make OutputResponse a JSON/Raw enum

### LINKED ISSUE #1317: [Bug]: `OutputResponse` is missing the raw bytes response
### Issue description

According to the Core API TIP the `/api/core/v2/outputs/{outputId}` endpoint should return raw bytes in addition to JSON.

### Version

`iota-types:1.0.0-rc`

### Expected behaviour

`OutputResponse` should follow the TIP.

### Actual behaviour

It does not :trollface: 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

_No response_

### Errors

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by thibault-martinez**
Fixes #1317 

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: types/src/api/response.rs [hunk 1]
```diff
@@ -302,6 +302,20 @@ impl OutputMetadataResponse {
     }
 }
 
+/// Response of GET /api/core/v2/outputs/{output_id}.
+/// Returns an output and its metadata as JSON or raw bytes.
```
Comment (Thoralf-M) [inline types/src/api/response.rs:306]: It's like this, right?
```suggestion
/// Returns an output and its metadata as JSON or only the output as raw bytes.
```

**Review by Thoralf-M — DISMISSED** [review]

**Review by grtlr — DISMISSED** [review]

**Review by Thoralf-M — APPROVED** [review]

**Review by samuel-rufi — APPROVED** [review]
