### PR TITLE
Fix regex of several MQTT topics

### LINKED ISSUE #1591: [Bug]: Unable to subscribe to MQTT Tagged Data Topic using NodeJs
### Issue description

Code Snippet used:
```js
import { Client, initLogger } from '@iota/client';

const client = new Client({
    nodes: ['https://api.testnet.shimmer.network'],
});

export async function subscribe(tag) {
    initLogger();

    // room hex encoded
    let tagHex = '0x' + Buffer.from(room, 'utf8').toString('hex');

    let roomTopic = 'blocks/tagged-data/' + tagHex;
    const topics = [roomTopic];
    console.log('topics:', topics);

    const callback = function (error, data) {
        console.log(JSON.parse(data));
    };
    await client.listen(topics, callback);

    // Clear listener after 10 seconds
    setTimeout(async () => {
        await client.clearListeners(['blocks']);
        console.log('Listener cleared');
        // Exit the process
        setTimeout(async () => process.exit(0), 2000);
    }, 10000);
}
```

### Version

`"@iota/client": "^3.0.0-rc.5",`

### Expected behaviour

Should subscribe to the MQTT Topic.

### Actual behaviour

Getting Error `InvalidMqttTopic("blocks/tagged-data/0x74657374")`

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Run the code above

### Errors

```sh
thread '<unnamed>' panicked at 'invalid MQTT topic: InvalidMqttTopic("blocks/tagged-data/0x74657374")', src/message_handler.rs:147:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/.../node_modules/@iota/client/out/lib/MessageHandler.js:17
        return (0, bindings_1.listen)(topics, callback, this.messageHandler);
                                     ^

Error: internal error in Neon module: invalid MQTT topic: InvalidMqttTopic("blocks/tagged-data/0x74657374")
...
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by thibault-martinez**
Fix https://github.com/iotaledger/iota.rs/issues/1591

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: client/src/node_api/mqtt/types.rs [hunk 1]
```diff
@@ -163,35 +163,34 @@ impl<'de> Deserialize<'de> for Topic {
...
-            r"^outputs/nft/0x([a-f0-9]{40})$",
-            r"^outputs/foundry/0x([a-f0-9]{52})$",
-            // BIP-173 compliant bech32 address
-            r"^outputs/unlock/(\+|address|storage-return|expiration|state-controller|governor|immutable-alias)/[\x21-\x7E]{1,30}1[A-Za-z0-9]+$",
-            // BIP-173 compliant bech32 address
-            r"^outputs/unlock/(\+|address|storage-return|expiration|state-controller|governor|immutable-alias)/[\x21-\x7E]{1,30}1[A-Za-z0-9]+/spent$",
+            // Output topics.
+            r"^outputs/0x([a-f0-9]{64})(\d{4})$",
+            r"^outputs/alias/0x([a-f0-9]{64})",
+            r"^outputs/nft/0x([a-f0-9]{64})",
```
Comment (Thoralf-M) [inline client/src/node_api/mqtt/types.rs]:
```suggestion
            r"^outputs/alias/0x([a-f0-9]{64})$",
            r"^outputs/nft/0x([a-f0-9]{64})$",
```
Shouldn't they also be like this? Same for ` r"^block-metadata/0x([a-f0-9]{64})",`

Comment (thibault-martinez) [reply client/src/node_api/mqtt/types.rs]: Ah yeah good catch, I messed up

**Review by Thoralf-M — APPROVED** [review]
